### PR TITLE
remove unwanted comma

### PR DESCRIPTION
**Pull request by paul-cheung**

### CODE REVIEW

**Comment by olprod** [comment]
OPS Build status updates of commit _[f8418b4](https://github.com/paul-cheung/microsoft-graph-docs.zh-CN/pull/2/commits/f8418b436b88afe1fcc27534d7606b941e0ba0f6)_: 

:clock10: **Preparing**: average preparing time is not available, there is no data for this repository.

**Comment by olprod** [comment]
OPS Build status updates of commit _[f8418b4](https://github.com/paul-cheung/microsoft-graph-docs.zh-CN/pull/2/commits/f8418b436b88afe1fcc27534d7606b941e0ba0f6)_: 

:clock10: **Incremental building**: average incremental building time is not available, there is no data for this repository.

**Comment by olprod** [comment]
OPS Build status updates of commit _[f8418b4](https://github.com/paul-cheung/microsoft-graph-docs.zh-CN/pull/2/commits/f8418b436b88afe1fcc27534d7606b941e0ba0f6)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[api-reference/v1.0/resources/channel.md](https://github.com/paul-cheung/microsoft-graph-docs.zh-CN/blob/typo-correction/api-reference/v1.0/resources/channel.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C20%5C50bdf68c-ba11-8701-2c52-0e250e4e8f8a%5CPullRequest%5C201902200426278183-2%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=rCgS8dDteiOaAnDT%2BFfW7hqpVr%2B7L0pky%2FOXK2otAII%3D&st=2019-02-20T04%3A25%3A10Z&se=2019-03-23T04%3A30%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by paul-cheung** [comment]
could this pull request be accepted?

**Comment by paul-cheung** [comment]
could this commit be merged?

**Pull request closed without merging**
